apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-sample
spec:
  selector:
    matchLabels:
      app: minikube-sample
  replicas: 1
  template:
    metadata:
      labels:
        app: minikube-sample
    spec:
      containers:
        - name: minikube-sample
          image: minikube-sample:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: env.namespace
              value: default
          volumeMounts:
            - name: application-config
              mountPath: "/deployments/config"
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: minikube-sample
            items:
              - key: application.properties
                path: application.properties